spring:
  profiles: local
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource-master:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mubeatdb?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://mubeat-dev-db-cluster.cluster-cuxtg5bg36lw.ap-northeast-2.rds.amazonaws.com:3306/mubeatdb?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: vlending
    password: vlending784
    maxIdle: 5
    initialSize: 1
    maxWait: 30000
    testOnBorrow: true
    validationQuery: SELECT 1
  datasource-slave:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mubeatdb?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    url: jdbc:mysql://mubeat-dev-db-cluster.cluster-ro-cuxtg5bg36lw.ap-northeast-2.rds.amazonaws.com:3306/mubeatdb?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: vlending
    password: vlending784
    maxIdle: 5
    initialSize: 1
    maxWait: 30000
    testOnBorrow: true
    validationQuery: SELECT 1
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
#    properties:
#      hibernate.format_sql: true
    database: mysql
    properties:
      hibernate.enable_lazy_load_no_trans: true
    database-platform: kr.mubeat.cms.hibernate.CustomMySQLDialect
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  elasticsearch:
    cluster-name: 608970008150:mubeat-es-dev
    host: search-mubeat-es-dev-xhvwyba4zssojfv3lfb57qz5oe.ap-northeast-2.es.amazonaws.com
#   cluster-name: 608970008150:devvlending
#    host: search-vlending-es-fhu34u5m6ykxspet4q5vixnkoe.ap-northeast-2.es.amazonaws.com
    port: 80
  aws:
    access-key: AKIAI4NXPLW6FHRQDPYQ
    secret-key: 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
    region: ap-northeast-2
    s3bucket: mubeat-cdn-dev-archive
    s3-output-bucket: mubeat-cdn-dev
    archive-bucket: mubeats3ftp
    s3-list-size: 1000
    spark-job-flow-id: j-2P6WNQ2T5KA2C
    default-input-key: artist
    distribution-id: E3TCNJ7N169EJ2
    cloudfront-url: https://dev.img.mubeat.tv/
    dynamodb-local-endpoint: http://ec2-52-78-104-61.ap-northeast-2.compute.amazonaws.com:8000
    dynamodb-local-signing-region: ap-northeast-2
  http:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
      enabled: true
logging:
  file: logs/mubeat_cms
  config: classpath:logback-spring.xml
server:
  port: 5000
  connection-timeout: 300000
  error:
    whitelabel:
      enabled: false

---

spring:
  profiles: dev
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource-master:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mubeat-dev-db-cluster.cluster-cuxtg5bg36lw.ap-northeast-2.rds.amazonaws.com:3306/mubeatdb?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: vlending
    password: vlending784
    maxIdle: 5
    initialSize: 1
    maxWait: 30000
    testOnBorrow: true
    validationQuery: SELECT 1
  datasource-slave:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mubeat-dev-db-cluster.cluster-ro-cuxtg5bg36lw.ap-northeast-2.rds.amazonaws.com:3306/mubeatdb?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: vlending
    password: vlending784
    maxIdle: 5
    initialSize: 1
    maxWait: 30000
    testOnBorrow: true
    validationQuery: SELECT 1
  redis:
#    host: localhost
    host: devrediscache.bkjlul.0001.apn2.cache.amazonaws.com
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
#    properties:
#      hibernate.format_sql: true
    database: mysql
    properties:
      hibernate.enable_lazy_load_no_trans: true
    database-platform: kr.mubeat.cms.hibernate.CustomMySQLDialect
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  elasticsearch:
    cluster-name: 608970008150:mubeat-es-dev
    host: search-mubeat-es-dev-xhvwyba4zssojfv3lfb57qz5oe.ap-northeast-2.es.amazonaws.com
#    cluster-name: 608970008150:devvlending1
#    host: search-devvlending-uspsrcnbnmzjl76txest5dty6q.ap-northeast-2.es.amazonaws.com
    port: 80
  aws:
    access-key: AKIAI4NXPLW6FHRQDPYQ
    secret-key: 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
    region: ap-northeast-2
    s3bucket: mubeat-cdn-dev-archive
    s3-output-bucket: mubeat-cdn-dev
    archive-bucket: mubeats3ftp
    s3-list-size: 1000
    spark-job-flow-id: j-2P6WNQ2T5KA2C
    default-input-key: artist
    distribution-id: E3TCNJ7N169EJ2
    cloudfront-url: https://dev.img.mubeat.tv/
    dynamodb-local-endpoint: http://ec2-52-78-104-61.ap-northeast-2.compute.amazonaws.com:8000
    dynamodb-local-signing-region: ap-northeast-2
  http:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
      enabled: true
api:
  url: https://dev.api.mubeat.tv/api/v1/cms/cookies?url=https://vod2.cms.mubeat.tv/clip/
logging:
  file: /data/server/logs/dev/mubeat_cms
  config: classpath:logback-spring.xml
server:
  port: 5001
  connection-timeout: 300000
  error:
    whitelabel:
      enabled: false
  session:
    cookie:
      domain: dev.cms.mubeat.tv

---

spring:
  profiles: live
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  datasource-master:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mubeat-cluster.cluster-cuxtg5bg36lw.ap-northeast-2.rds.amazonaws.com:3306/mubeatdb?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: vlending
    password: vlending784
    maxIdle: 1
    initialSize: 2
    maxActive: 2
    maxWait: 30000
    testOnBorrow: true
    validationQuery: SELECT 1
  datasource-slave:
    type: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://mubeat-cluster.cluster-ro-cuxtg5bg36lw.ap-northeast-2.rds.amazonaws.com:3306/mubeatdb?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: vlending
    password: vlending784
    maxIdle: 1
    initialSize: 2
    maxActive: 2
    maxWait: 30000
    testOnBorrow: true
    validationQuery: SELECT 1
  redis:
    host: devrediscache.bkjlul.0001.apn2.cache.amazonaws.com
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
#    properties:
#      hibernate.format_sql: true
    database: mysql
    properties:
      hibernate.enable_lazy_load_no_trans: true
    database-platform: kr.mubeat.cms.hibernate.CustomMySQLDialect
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  elasticsearch:
    cluster-name: 608970008150:mubeat-es-live
    host: search-mubeat-es-live-awubqkyqrhbqmbesmowkbbbrrm.ap-northeast-2.es.amazonaws.com
#    cluster-name: 608970008150:vlending-es
#    host: search-vlending-es-fhu34u5m6ykxspet4q5vixnkoe.ap-northeast-2.es.amazonaws.com
    port : 80
  aws:
    access-key: AKIAI4NXPLW6FHRQDPYQ
    secret-key: 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
    region: ap-northeast-2
    s3bucket: mubeat-cdn-archive
    s3-output-bucket: mubeat-cdn
    archive-bucket: mubeats3ftp
    s3-list-size: 1000
    spark-job-flow-id: j-2P6WNQ2T5KA2C
    default-input-key: artist
    distribution-id: E3TCNJ7N169EJ2
    cloudfront-url: https://img.mubeat.tv/
    dynamodb-local-endpoint: http://dynamodb.ap-northeast-2.amazonaws.com
    dynamodb-local-signing-region: ap-northeast-2
  http:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
      enabled: true
api:
  url: https://api.mubeat.tv/api/v1/cms/cookies?url=https://vod2.cms.mubeat.tv/clip/
logging:
#  file: logs/mubeat_cms
  file: /data/server/logs/live/mubeat_cms
  config: classpath:logback-spring.xml
server:
  port: 5000
  connection-timeout: 300000
  error:
    whitelabel:
      enabled: false
  session:
    cookie:
      domain: cms.mubeat.tv